### ISSUE TITLE
Arguments are broken

### ISSUE THREAD

**Issue by xf-** [klattimer/LGWebOSRemote#118]
The CLI worked fine for long time, but now every command with argument fails
```
<tv_name> startApp <appid>
```
results in
```
Error: Argument lengths do not match
```

Tried `zsh` and `bash` (just to avoid some unrelated issue).

**Comment by klattimer** [comment]
I believe this is fixed in a recently merged PR.

**Comment by xf-** [comment]
@klattimer The error is gone, but it feels completely broken. I get no output at all.

### Existing config
(No IP change - I can ping and scan it)
```bash
lgtv TV swInfo
```

### After deleting config
- Scan works (result OK)
- Auth fails

Output for auth
```
Traceback (most recent call last):
  File "/usr/bin/lgtv", line 33, in <module>
    sys.exit(load_entry_point('LGTV==0.3', 'console_scripts', 'lgtv')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/LGTV/__init__.py", line 160, in main
    ws.connect()
  File "/usr/lib/python3.11/site-packages/ws4py/client/__init__.py", line 224, in connect
    bytes = self.sock.recv(128)
            ^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by Tenzer** [comment]
@xf- You now need to run the commands as `lgtv --name TV swInfo` or `lgtv -n TV swInfo`.
