### ISSUE TITLE
Can't auth with TV

### ISSUE THREAD

**Issue by elomeno** [klattimer/LGWebOSRemote#130]
DEBUG:getmac:Initializing 'ip4' method cache (platform: 'darwin')
DEBUG:getmac:Finished initializing 'ip4' method cache
DEBUG:getmac:Raw MAC found: b4:b2:91:c4:b3:4b
Traceback (most recent call last):
  File "/opt/lgtv-venv/bin/lgtv", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/lgtv-venv/lib/python3.12/site-packages/LGTV/__init__.py", line 150, in main
    ws.connect()
  File "/opt/lgtv-venv/lib/python3.12/site-packages/ws4py/client/__init__.py", line 214, in connect
    self.sock = ssl.wrap_socket(self.sock, **self.ssl_options)
                ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'

**Comment by asebert-caue** [comment]
Can someone help us with the same issue ?

``` bash
❯lgtv auth 194.107.100.42 mytv ssl
DEBUG:getmac:Initializing 'ip4' method cache (platform: 'darwin')
DEBUG:getmac:Finished initializing 'ip4' method cache
DEBUG:getmac:Raw MAC found: 80:5b:65:a5:f8:4
DEBUG:getmac:Length of MAC 80:5b:65:a5:f8:4 is 16, padding single-character octets with zeros
Traceback (most recent call last):
  File "/Users/asebert/.local/bin/lgtv", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/asebert/.local/pipx/venvs/lgtv/lib/python3.12/site-packages/LGTV/__init__.py", line 150, in main
    ws.connect()
  File "/Users/asebert/.local/pipx/venvs/lgtv/lib/python3.12/site-packages/ws4py/client/__init__.py", line 214, in connect
    self.sock = ssl.wrap_socket(self.sock, **self.ssl_options)
                ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```

**Comment by klattimer** [comment]
This isn't a problem with LGTV, it's a problem with ws4py. 

Upstream issue appears to be tracked here: https://github.com/Lawouach/WebSocket-for-Python/issues/262
