### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'exclude_headers'

### ISSUE THREAD

**Issue by beltsonata** [klattimer/LGWebOSRemote#3]
When I do 

python lgtv.py auth <IP_ADDRESS>

I get:

> Traceback (most recent call last):
>   File "lgtv.py", line 484, in <module>
>     ws = LGTVClient()
>   File "lgtv.py", line 215, in __init__
>     super(LGTVClient, self).__init__('ws://' + self.__hostname + ':3000/', exclude_headers=["Origin"])
> TypeError: __init__() got an unexpected keyword argument 'exclude_headers'

**Comment by beltsonata** [comment]
Sorry, looks like this was already reported https://github.com/klattimer/LGWebOSRemote/issues/1
