### ISSUE TITLE
I messed up something...

### ISSUE THREAD

**Issue by irmantask** [klattimer/LGWebOSRemote#51]
Hey,

i messed up something something... 😅

When i try to run `lgtv scan`:
> timed out
> timed out
> timed out

`$ cat ~/.lgtv.json`
> cat: /home/pi/.lgtv.json: No such file or directory

But `lgtv on` and `lgtv off` are working fine 🤔

But when i run `lgtv mute` or other command i get
> Traceback (most recent call last):
>   File "/usr/local/bin/lgtv", line 11, in <module>
>     load_entry_point('LGTV==0.1.2', 'console_scripts', 'lgtv')()
>   File "build/bdist.linux-armv7l/egg/LGTV/main.py", line 86, in main
>   File "build/bdist.linux-armv7l/egg/LGTV/__init__.py", line 225, in __init__
> TypeError: cannot concatenate 'str' and 'NoneType' objects

Using Raspberry Pi 3 B+ with Raspbian Buster

**Comment by irmantask** [comment]
Now using Hassio instead :)
