### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by DarkCeptor44** [klattimer/LGWebOSRemote#59]
How to reproduce: `lgtv <TVName> volumeDown`.

Full tracelog:
```
Traceback (most recent call last):
  File "c:\program files\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\program files\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "h:\programacao\python\lgtv-os\lgwebosremote\venv-git\lib\site-packages\ws4py\webso
cket.py", line 531, in run
    self.terminate()
  File "h:\programacao\python\lgtv-os\lgwebosremote\venv-git\lib\site-packages\ws4py\webso
cket.py", line 431, in terminate
    self.closed(1006, "Going away")
  File "h:\programacao\python\lgtv-os\lgwebosremote\venv-git\lib\site-packages\LGTV\remote
.py", line 87, in closed
    "reason": reason.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by sobertram** [comment]
Interesting, I am not having an issue with volumeUp or volumeDown. 

lgtv lg1 volumeDown
{"closing": {"reason": "", "code": 1000}}

And I verify that the volume goes down by one. Could the TV version be the issue?

I am using UK6300PUE.

**Comment by DarkCeptor44** [comment]
Everything works for me too, it just shows the error which is not right because it can confuse people.
