### ISSUE TITLE
lgtv Auth "error"

### ISSUE THREAD

**Issue by M7anu** [klattimer/LGWebOSRemote#65]
Hello,
I have a problem with command "lgtv auth" she return an error "filenotfounderror"
capture: 
```
Microsoft Windows [version 10.0.19041.388]
(c) 2020 Microsoft Corporation. Tous droits réservés.

C:\WINDOWS\system32>lgtv auth 192.168.1.12 TV
Traceback (most recent call last):
  File "C:\Users\Manu\AppData\Local\Programs\Python\Python38\Scripts\lgtv-script.py", line 11, in <module>
    load_entry_point('LGTV==0.2', 'console_scripts', 'lgtv')()
  File "c:\users\manu\appdata\local\programs\python\python38\lib\site-packages\LGTV\__init__.py", line 137, in main
    ws = LGTVAuth(name, host)
  File "c:\users\manu\appdata\local\programs\python\python38\lib\site-packages\LGTV\auth.py", line 28, in __init__
    self.__macAddress = self.__get_mac_address(self.__ip)
  File "c:\users\manu\appdata\local\programs\python\python38\lib\site-packages\LGTV\auth.py", line 51, in __get_mac_address
    pid = subprocess.Popen(["ip", "n", "s", address], stdout=subprocess.PIPE)
  File "c:\users\manu\appdata\local\programs\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\manu\appdata\local\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

C:\WINDOWS\system32>
```
The problem is the new protocol of identification of the TV (tv version 5.10.45) because no pin code on my tv when i want use this command-line ?
My tv information:
`{"result": "ok", "count": 1, "list": [{"uuid": "c86395c0-a764-0bbe-d015-2dc5dc120d7d", "model": "OLED55C8PLA", "address": "192.168.1.12"}]}`
Or i have an issue in my installation ?
Thank for your work on this application.

**Comment by klattimer** [comment]
This project does not support windows.
