### ISSUE TITLE
TypeError: Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by arkonbob** [klattimer/LGWebOSRemote#70]
Every command was failing for me with `TypeError: Object of type 'bytes' is not JSON serializable`.

The following edit to `lgtv-venv/lib/python3.8/site-packages/LGTV/remote.py`, copy pasted from StackOverflow, resolves the issue although the printed reason now has no obvious meaning.

```
  83     def closed(self, code, reason: str = None):
  84         encoded = base64.b64encode(b'reason')
  85         decoded  = encoded.decode('ascii')
  86         print (json.dumps({
  87             "closing": {
  88                 "code": code,
  89                 "reason": decoded
  90 #                "reason": reason
  91             }
  92         }))
```

**Comment by klattimer** [comment]
The code provided here is nonsense, it takes the byte string b'reason' which is literally just "reason". 

`if type(reason) == bytes: reason = reason.decode('utf-8')`

is probably all that's needed

**Comment by grrosminet** [comment]
Got the same when trying to send a notificationWithIcon
```
(lgtv-venv) pi@pi2:~ $ lgtv TV notificationWithIcon "Le portail est ouvert !" "http://192.168.0.251/images/portail48_On.png"
DEBUG:root:Initiating handshake
DEBUG:root:Received response 
DEBUG:root:{"type":"registered","id":"register_0","payload":{"client-key":"b6bd372cbf43c0a85b57fcf26ffa4129"}}  
DEBUG:root:Handshake complete  
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.0.251:80  
DEBUG:urllib3.connectionpool:http://192.168.0.251:80 "GET /images/portail48_On.png HTTP/1.1" 200 855  
{"closing": {"code": 1006, "reason": "Going away"}}  
Exception in thread WebSocketClient:  
Traceback (most recent call last):  
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner  
    self.run()  
  File "/usr/lib/python3.7/threading.py", line 865, in run  
    self._target(*self._args, **self._kwargs)  
  File "/home/pi/lgtv-venv/lib/python3.7/site-packages/ws4py/websocket.py", line 528, in run  
    if not self.once():  
  File "/home/pi/lgtv-venv/lib/python3.7/site-packages/ws4py/websocket.py", line 410, in once  
    if not self.process(self.buf[:requested]):  
  File "/home/pi/lgtv-venv/lib/python3.7/site-packages/ws4py/websocket.py", line 480, in process  
    self.received_message(s.message)  
  File "/home/pi/lgtv-venv/lib/python3.7/site-packages/LGTV/remote.py", line 95, in received_message  
    self.__waiting_callback(json.loads(str(response)))  
  File "/home/pi/lgtv-venv/lib/python3.7/site-packages/LGTV/remote.py", line 104, in __handshake  
    self.__execute()  
  File "/home/pi/lgtv-venv/lib/python3.7/site-packages/LGTV/remote.py", line 114, in __execute
    self.__class__.__dict__[method](self, **args)
  File "/home/pi/lgtv-venv/lib/python3.7/site-packages/LGTV/remote.py", line 182, in notificationWithIcon
    self.__send_command("request", "ssap://system.notifications/createToast", data, callback)
  File "/home/pi/lgtv-venv/lib/python3.7/site-packages/LGTV/remote.py", line 148, in __send_command
    payload = json.dumps(payload)
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

what can I do to help debugging ?

Output of my "swInfo" :
```
{
   "type":"response",
   "id":"sw_info_0",
   "payload":{
      "returnValue":true,
      "product_name":"webOSTV 3.0",
      "model_name":"HE_DTV_W16N_AFADABAA",
      "sw_type":"FIRMWARE",
      "major_ver":"05",
      "minor_ver":"50.95",
      "country":"EU7",
      "country_group":"EU",
      "device_id":"c8:08:e9:c4:41:d2",
      "auth_flag":"N",
      "ignore_disable":"N",
      "eco_info":"01",
      "config_key":"00",
      "language_code":"fr-FR"
   }
}
```

**Comment by klattimer** [comment]
committed a fix.
